### ISSUE TITLE
NullReferenceException using Learner

### ISSUE THREAD

**Issue by fdbarroso** [sethjuarez/numl#24]
Hi!
I'm using the example provided in the "Getting Started" section, and I'm constantly getting `NullReferenceException` when using the `Learner`.
The exception occurs on `Ject.GetCtor`. If I substitute the `Parallel.For` on the `Learner` for a normal `For`, the exceptions disappear.

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
       at numl.Utils.Ject.GetCtor(Type type) in c:\projects\numl\numl\Utils\Ject.cs:line 182
       at numl.Utils.Ject.Create(Type type) in c:\projects\numl\numl\Utils\Ject.cs:line 195
       at numl.Supervised.DecisionTree.DecisionTreeGenerator.GetBestSplit(Matrix x, Vector y, List`1 used) in c:\projects\numl\numl\Supervised\DecisionTree\DecisionTreeGenerator.cs:line 215
       at numl.Supervised.DecisionTree.DecisionTreeGenerator.BuildTree(Matrix x, Vector y, Int32 depth, List`1 used) in c:\projects\numl\numl\Supervised\DecisionTree\DecisionTreeGenerator.cs:line 112
       at numl.Supervised.DecisionTree.DecisionTreeGenerator.Generate(Matrix x, Vector y) in c:\projects\numl\numl\Supervised\DecisionTree\DecisionTreeGenerator.cs:line 92
       at numl.Learner.GenerateModel(IGenerator generator, Matrix x, Vector y, IEnumerable`1 examples, Double trainingPct, Int32 total) in c:\projects\numl\numl\Learner.cs:line 145
       at numl.Learner.<>c__DisplayClasse.<Learn>b__d(Int32 i) in c:\projects\numl\numl\Learner.cs:line 111
       at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
  InnerException: 
```

**Comment by sethjuarez** [comment]
I encountered this a bit ago :(.

**Comment by Moisessoares** [comment]
Descriptor  should be thread safe

**Comment by DashNY** [comment]
I'm having the same problem with DecisionTreeGenerator. The error is intermittent, only happens sometimes.

Thanks,


System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
       at numl.Utils.Ject.GetCtor(Type type) in c:\projects\numl\numl\Utils\Ject.cs:line 182
       at numl.Utils.Ject.Create(Type type) in c:\projects\numl\numl\Utils\Ject.cs:line 195
       at numl.Supervised.DecisionTree.DecisionTreeGenerator.GetBestSplit(Matrix x, Vector y, List`1 used) in c:\projects\numl\numl\Supervised\DecisionTree\DecisionTreeGenerator.cs:line 215
       at numl.Supervised.DecisionTree.DecisionTreeGenerator.BuildTree(Matrix x, Vector y, Int32 depth, List`1 used) in c:\projects\numl\numl\Supervised\DecisionTree\DecisionTreeGenerator.cs:line 112
       at numl.Supervised.DecisionTree.DecisionTreeGenerator.Generate(Matrix x, Vector y) in c:\projects\numl\numl\Supervised\DecisionTree\DecisionTreeGenerator.cs:line 92
       at numl.Learner.GenerateModel(IGenerator generator, Matrix x, Vector y, IEnumerable`1 examples, Double trainingPct, Int32 total) in c:\projects\numl\numl\Learner.cs:line 145
       at numl.Learner.<>c__DisplayClasse.<Learn>b__d(Int32 i) in c:\projects\numl\numl\Learner.cs:line 111
       at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
  InnerException:

**Comment by sethjuarez** [comment]
The descriptor itself is not the problem. It is happening with the fast reflector called Ject. Unfortunately it is hard to replicate with the tests :(

I am looking into it right now.
