### ISSUE TITLE
Model.Load(string) fails for KernelPerceptronGenerator

### ISSUE THREAD

**Issue by DashNY** [sethjuarez/numl#29]
Seth,

Could you please fix the Load functionality for KernelPerceptron? Thanks.
This code fails:

```cs
            var data = new List<MyData>();
            for (var i = 0; i < 100; i++)
            {
                data.Add(new MyData { Prop1 = i, Prop2 = i + 1, Prop3 = i + 2, Result = i % 2 == 0 });
            }
            var descriptor = Descriptor.Create<MyData>();

            var kernel = new RBFKernel(3);
            var generator = new KernelPerceptronGenerator(kernel) { Descriptor = descriptor };

            var learningModel = Learner.Learn(data, 0.80, 1000, generator);
            Console.WriteLine(learningModel);

            learningModel.Model.Save("model.mdl");
            // THIS FAILS ----
            learningModel.Model.Load("model.mdl");
```

Error:

```

There is an error in XML document (2, 2). ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at numl.Supervised.Perceptron.KernelPerceptronModel.ReadXml(XmlReader reader) in c:\projects\numl\numl\Supervised\Perceptron\KernelPerceptronModel.cs:line 63
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderKernelPerceptronModel.Read1_KernelPerceptronModel()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at numl.Utils.Xml.Load(String file, Type t) in c:\projects\numl\numl\Utils\Xml.cs:line 94
   at numl.Supervised.Model.Load(String file) in c:\projects\numl\numl\Supervised\Model.cs:line 75

```

**Comment by sethjuarez** [comment]
Uh oh. I will take a look.

**Comment by sethjuarez** [comment]
I made a couple of changes (but managed to find the error):

```cs
var data = new List<object>();
for (var i = 0; i < 100; i++)
{
    data.Add(new { Prop1 = i, Prop2 = i + 1, Prop3 = i + 2, Result = i % 2 == 0 });
}
var descriptor = Descriptor.Create(typeof(object))
                            .With("Prop1").As(typeof(int))
                            .With("Prop2").As(typeof(int))
                            .With("Prop3").As(typeof(int))
                            .Learn("Result").As(typeof(bool));

var kernel = new RBFKernel(3);
var generator = new KernelPerceptronGenerator(kernel) { Descriptor = descriptor };

var learningModel = Learner.Learn(data, 0.80, 1000, generator);
Console.WriteLine(learningModel);

learningModel.Model.Save("model.mdl");
// THIS FAILS ----
learningModel.Model.Load("model.mdl");
```

**Comment by sethjuarez** [comment]
Haven't forgotten, just in the middle of changing out all serialization (sorry for the delay!)

**Comment by sethjuarez** [comment]
This should work now.
