### ISSUE TITLE
Large Integer/Double Error during Prediction

### ISSUE THREAD

**Issue by IlungP** [sethjuarez/numl#45]
Hi,

I created 2 models ( Decision Tree and Neural Network models) on the classification dataset that I have. The models were created fine but I face an error when doing the prediction with either of these models (using code `Model.Predict<Class>Object`). The error was due to the conversion of double to int32 for features that have large numbers (10000 or more). I created a class for the data record objects and had specified double for all features. However, the numl code (Ject class) automatically converts double to Int32 for reasons that I could not understand. When looking at the Ject, Property & model classes, I could not comprehend where the type T is specified and why it is specified as Int32. Here are the error message and stack trace. Appreciate your help.

Value was either too large or too small for an Int32.

at System.Convert.ToInt32(Double value)
   at System.Double.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at numl.Utils.Ject.Convert(Double val, Type t) in c:\projects\numl\numl\Utils\Ject.cs:line 313
   at numl.Model.Property.Convert(Double val) in c:\projects\numl\numl\Model\Property.cs:line 79
   at numl.Supervised.Model.Predict(Object o) in c:\projects\numl\numl\Supervised\Model.cs:line 38
   at numl.Supervised.Model.Predict[T](T o) in c:\projects\numl\numl\Supervised\Model.cs:line 48
   at WebSecurityRatingApp.Default.btnTwitter_Click(Object sender, EventArgs e)

**Comment by bdschrisk** [comment]
Hey,

It looks like your label attribute is an Int32 - would that be right?

Can you try converting the model object to a Vector form using the instantiated Descriptor object - see Descriptor.Convert(object item, bool withLabel).  Pass in false for the withLabel property.  Then pass the double array to the model Predict method and reply back here with the predicted output (raw value) from the model.

My guess is that one of the features of this specific test item is causing an issue.  Can you check the features against the ones used at training time?

Also can you tell us which build you're using?

Thanks.

**Comment by IlungP** [comment]
Hi

Yes, you were probably correct. I actually used enum for the label similar to the example shown in [here](http://www.refactorthis.net/post/2013/03/26/numl-a-machine-learning-library-for-NET-developers.aspx). The label has only two categories good or bad. 

I tried double for the label and the library finally works. I used the latest stable build 0.8.26. Thanks for your help.
